### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ReleaseBug** [imxieyi/esp32-rgb-homebridge#1]
Hi ,I find a memory leak issue.

FILE: main.cpp  LINE:71　temp=(char*)malloc(2);
FILE: httpserver-netconn.c  LINE:87　char* ret=cmd_callback(getcmd(buf));

Ret should be released, is right ?

**Comment by imxieyi** [comment]
Well... That's a real problem. Thank you for your correction.

**Comment by ReleaseBug** [comment]
Wonderful&Niubility!
Proud of You!
